"""add email verification fields

Revision ID: 3276265ec499
Revises: 
Create Date: 2026-07-31 00:21:46.796846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3276265ec499'
down_revision = 'e613322183e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=False)

    # ### end Alembic commands ###

    # Grandfather existing rows to verified (server_default above), then drop
    # the column-level default now that they've been backfilled: otherwise
    # any future non-ORM insert (bulk import, admin script, raw SQL) would
    # silently create a pre-verified account by default, and `flask db
    # migrate` autogenerate would see a spurious diff against the model
    # (which never declares a default).
    #
    # This MUST be its own batch_alter_table block, not folded into the one
    # above. On SQLite, batch mode defers every op in a single `with` block
    # to one table recreation using the block's *final* column state, and
    # copies old rows via `INSERT INTO new_table (<cols>) SELECT <cols> FROM
    # old_table` - omitting any column that doesn't exist yet in the old
    # table and relying on that column's server_default to backfill it at
    # insert time. If server_default=None were applied in the same block,
    # the recreation would have no default to fall back on for the
    # newly-added, not-yet-populated email_verified column, and the backfill
    # would fail with a NOT NULL constraint violation. Splitting into a
    # second block lets the first recreation finish (and actually backfill
    # every row to True) before the default is removed from the schema.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
