"""add signup attempt rate limiting

Revision ID: 93c65b745dbc
Revises: 3276265ec499
Create Date: 2026-07-31 19:36:14.897482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c65b745dbc'
down_revision = '3276265ec499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_attempts_ip_hash'), ['ip_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signup_attempts_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_signup_attempts_created_at'))

    op.drop_table('signup_attempts')
    # ### end Alembic commands ###
