"""baseline schema (pre email-verification)

Revision ID: e613322183e3
Revises:
Create Date: 2026-07-31 00:00:00.000000

This is the missing root migration. Commit e2a5fd1 removed db.create_all()
from init_db() on the assumption that Alembic's migration history already
covered the full schema. It didn't: the only migration that existed
(3276265ec499_add_email_verification_fields) was autogenerated against a
database that already had the `users`, `optimization_history`, and
`user_settings` tables, so it only contains `add_column`/`create_index`
operations against `users` - it never CREATEs any table. On a truly empty
database, `flask db upgrade` would therefore try to ALTER a `users` table
that doesn't exist and fail with `NoSuchTableError`.

This migration creates the three tables exactly as they existed BEFORE the
email-verification feature (i.e. `users` WITHOUT `email_verified`,
`verification_token`, `verification_token_expires` - those are added by
3276265ec499, which is chained on top of this one via its down_revision).

IMPORTANT - idempotency guard:
Production's live Postgres database already has these three tables (created
originally by the old, pre-Alembic db.create_all() bootstrapping) and has no
`alembic_version` row yet, so this migration is the first thing Alembic ever
runs against it. A plain `op.create_table(...)` would fail there with
"relation already exists". Guarding each create_table with a runtime
`inspect(conn).get_table_names()` check makes this migration a no-op for
tables that already exist (production) while still creating the full schema
from scratch on any genuinely empty database (fresh Railway environment,
staging, disaster recovery, local dev) - with no manual `flask db stamp`
step required anywhere. Do NOT "simplify" this by removing the guard and
just calling create_table unconditionally; that reintroduces the production
crash this comment is warning about.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e613322183e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    existing = set(inspect(conn).get_table_names())

    if 'users' not in existing:
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('password', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    if 'optimization_history' not in existing:
        op.create_table(
            'optimization_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('input_text', sa.Text(), nullable=False),
            sa.Column('output_text', sa.Text(), nullable=False),
            sa.Column('provider', sa.String(length=50), nullable=False),
            sa.Column('style', sa.String(length=50), nullable=True),
            sa.Column('input_tokens', sa.Integer(), nullable=True),
            sa.Column('output_tokens', sa.Integer(), nullable=True),
            sa.Column('reduction_percent', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('optimization_history', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_optimization_history_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_optimization_history_created_at'), ['created_at'], unique=False)

    if 'user_settings' not in existing:
        op.create_table(
            'user_settings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('preferred_provider', sa.String(length=50), nullable=True),
            sa.Column('preferred_style', sa.String(length=50), nullable=True),
            sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id'),
        )


def downgrade():
    # Reverse order for FK safety: child tables before the `users` table
    # they reference.
    op.drop_table('user_settings')
    op.drop_table('optimization_history')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
    op.drop_table('users')
